### ISSUE TITLE
Better handling of None

### ISSUE THREAD

**Issue by cthoyt** [scolby33/easy_config#18]
When you stick a `None` somewhere there is a non-optional argument, the help information is very cryptic:

```python-traceback
$ pybel-git ci_gitlab
Traceback (most recent call last):
  File "/Users/cthoyt/.virtualenvs/hbp/bin/pybel-git", line 11, in <module>
    load_entry_point('pybel-git', 'console_scripts', 'pybel-git')()
  File "/Users/cthoyt/.virtualenvs/hbp/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/cthoyt/.virtualenvs/hbp/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/cthoyt/.virtualenvs/hbp/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/cthoyt/.virtualenvs/hbp/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/cthoyt/.virtualenvs/hbp/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/cthoyt/dev/pybel-git/src/pybel_git/cli.py", line 70, in ci_gitlab
    token=token,
  File "/Users/cthoyt/.virtualenvs/hbp/lib/python3.7/site-packages/easy_config/__init__.py", line 206, in load
    values.update(cls._load_dict(kwargs))
  File "/Users/cthoyt/.virtualenvs/hbp/lib/python3.7/site-packages/easy_config/__init__.py", line 157, in _load_dict
    for field in dataclasses.fields(cls)
  File "/Users/cthoyt/.virtualenvs/hbp/lib/python3.7/site-packages/easy_config/__init__.py", line 158, in <dictcomp>
    if field.name in d
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

Re:

https://github.com/scolby33/easy_config/blob/69d348e62376f7aac6520354b3b340d5a89dbc23/src/easy_config/__init__.py#L156-L160

That `if field.name in d` isn't enough, the `d[field.name]` should be checked for none-ness and handled.

**Comment by scolby33** [comment]
How would you write this?
```python
non_optional_d = {k: v for k, v in d.items() if v is not None}
return {
    ...
    if field.name in non_optional_d
}
```

```python
return {
    ...
    if field.name in {k: v for k, v in d.items() if v is not None}
}
```

```python
return {
    ...
    if field.name in dict(filter(lambda item: item[1] is not None, d.items()))
}
```

**Comment by scolby33** [comment]
Actually, this is just a special case of something I considered and decided *not* to handle. Where is the `None` coming from in this case? I specifically decided that if you have an `int` field and your config file (for example) contained `"foo"` I wasn't gonna put any error handling in...it just calls `int("foo")` and it's up to the caller to deal with it. Considering this now, it might not be the most ergonomic API. Alternatives include:
- filtering out the bad values (which amounts to silently ignoring things)
- filtering out the bad values and logging a warning
- blowing up like it does now
- blowing up in a "nicer" manner with a better error message than `int() argument must be a string, a bytes-like object or a number, not 'NoneType'`

Thoughts?

**Comment by cthoyt** [comment]
I guess the only real problem here is the error given isn't useful for the user if they don't know what's going on. I would vote for blowing up in a "nicer" manner
